"""nullable x and y fields

Revision ID: 382e0bac0f88
Revises: None
Create Date: 2013-06-28 14:45:44.226586

"""

# revision identifiers, used by Alembic.
revision = '382e0bac0f88'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart', u'y_field_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('chart', u'x_field_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart', u'x_field_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('chart', u'y_field_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    ### end Alembic commands ###
